#数据源
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/project2?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
#mybatis---mapper的扫描路径    
  mvc:
    view:
      prefix: /WEB-INF/jsp
      suffix: .jsp

mybatis:
  mapper-locations:
  - classpath:mapper/*.xml

logging:
  level:
    com.st.dao: debug
    